package com.hemebiotech.analytics;
import java.util.List;
import java.util.TreeMap;

/**
 * @author Diane L'huillier
 *
 */
public class AnalyticsCounter {


	public static void main(String args[]) throws Exception {

		//Input will be generated by ReadSymptomDataFromFile and classed in an TreeMap : for organization 
		TreeMap<String, Integer> results;
		results = new TreeMap<String, Integer>();

		//Reader
		ISymptomReader iSymptomReader = new ReadSymptomDataFromFile("symptoms.txt");
		List<String>listOfSymptoms = iSymptomReader.getSymptoms();

		//Counter
		ISymptomsCounter iSymptomsCounter = new SymptomsCounter();
		results = iSymptomsCounter.occurences(listOfSymptoms);

		//Printer
		ISymptomsPrinter iSymptomsPrinter = new SymptomsPrinter();
		iSymptomsPrinter.output(results);	
	}
}
