package com.hemebiotech.analytics;
import java.util.List;
import java.util.TreeMap;

/**
 * <h1>Main : Read, Count and Print<h1>
 * @author Diane L'huillier
 * @version 2.0
 * @since 20/12/2020
 */
public class AnalyticsCounter {


	/**
	 * @param args
	 * @throws Exception
	 */
	public static void main(String args[]) throws Exception {

		//Input will be generated by ReadSymptomDataFromFile and classed in an TreeMap : for organization 
		TreeMap<String, Integer> results;
		results = new TreeMap<String, Integer>();

		//Reader
		ISymptomReader iSymptomReader = new ReadSymptomDataFromFile("symptoms.txt");
		List<String>listOfSymptoms = iSymptomReader.getSymptoms();

		//Counter
		ISymptomsCounter iSymptomsCounter = new SymptomsCounter();
		results = iSymptomsCounter.occurrences(listOfSymptoms);

		//Printer
		ISymptomsPrinter iSymptomsPrinter = new SymptomsPrinter();
		iSymptomsPrinter.output(results);	
	}
}
